image: Visual Studio 2019
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaHullIconGenerator" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore XwaHullIconGenerator\XwaHullIconGenerator.sln

build:
  project: XwaHullIconGenerator\XwaHullIconGenerator.sln
  verbosity: minimal

after_build:
- XwaHullIconGenerator\build-dist.cmd

artifacts:
- path: XwaHullIconGenerator\dist
  name: XwaHullIconGenerator-$(APPVEYOR_BUILD_VERSION)
  type: zip
